# Generated by Django 3.1.4 on 2021-03-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210321_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='final_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='midterm_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='prelim_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='sem_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='sem_status',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=0, max_length=50, null=True),
        ),
    ]
